SET PROCEXIM(PROC) "PROC for exchange possibility between areas AAA"
/                                                                   
ProcEximTruck_W                                                     
ProcEximTruck_S                                                     
ProcEximShip                                                        
ProcEximTruckC                                                      
                                                                    
/;                                                                  
