SET BIGAAAOPTIFLOW(AAA)                                                                                                                                                                       
/                                                                                                                                                                                             
Esbjerg                                                                                                                                                                                       
Koebenhavn                                                                                                                                                                                    
Odense                                                                                                                                                                                        
Aalborg                                                                                                                                                                                       
Aarhus                                                                                                                                                                                        
Middelfart                                                                                                                      !! TVIS district heating area                                 
Fredericia                                                                                                                      !! TVIS district heating area                                 
Vejle                                                                                                                           !! TVIS district heating area                                 
Kolding                                                                                                                         !! TVIS district heating area                                 
/                                                                                                                                                                                             
                                                                                                                                                                                              
SET CCSAAAOPTIFLOW(AAA)                                                                                                                                                                       
/                                                                                                                                                                                             
Kalundborg                                                                                                                                                                                    
Soroe                                                                                                                                                                                         
Lolland                                                                                                                                                                                       
Randers                                                                                                                                                                                       
/;                                                                                                                                                                                            
                                                                                                                                                                                              
SET REGHOV(AAA)                                                                                                                                                                               
/                                                                                                                                                                                             
Albertslund                                                                                                                                                                                   
Alleroed                                                                                                                                                                                      
Ballerup                                                                                                                                                                                      
Bornholm                                                                                                                                                                                      
Broendby                                                                                                                                                                                      
Christiansoe                                                                                                                                                                                  
Dragoer                                                                                                                                                                                       
Egedal                                                                                                                                                                                        
Fredensborg                                                                                                                                                                                   
Frederiksberg                                                                                                                                                                                 
Frederikssund                                                                                                                                                                                 
Furesoe                                                                                                                                                                                       
Gentofte                                                                                                                                                                                      
Gladsaxe                                                                                                                                                                                      
Glostrup                                                                                                                                                                                      
Gribskov                                                                                                                                                                                      
Halsnaes                                                                                                                                                                                      
Helsingoer                                                                                                                                                                                    
Herlev                                                                                                                                                                                        
Hilleroed                                                                                                                                                                                     
Hvidovre                                                                                                                                                                                      
Hoeje_Taastrup                                                                                                                                                                                
Hoersholm                                                                                                                                                                                     
Ishoej                                                                                                                                                                                        
Koebenhavn                                                                                                                                                                                    
Lyngby-Taarbaek                                                                                                                                                                               
Rudersdal                                                                                                                                                                                     
Roedovre                                                                                                                                                                                      
Taarnby                                                                                                                                                                                       
Vallensbaek                                                                                                                                                                                   
/;                                                                                                                                                                                            
                                                                                                                                                                                              
SET REGSJA(AAA)                                                                                                                                                                               
/                                                                                                                                                                                             
Faxe                                                                                                                                                                                          
Greve                                                                                                                                                                                         
Guldborgsund                                                                                                                                                                                  
Holbaek                                                                                                                                                                                       
Kalundborg                                                                                                                                                                                    
Koege                                                                                                                                                                                         
Lejre                                                                                                                                                                                         
Lolland                                                                                                                                                                                       
Naestved                                                                                                                                                                                      
Odsherred                                                                                                                                                                                     
Ringsted                                                                                                                                                                                      
Roskilde                                                                                                                                                                                      
Slagelse                                                                                                                                                                                      
Solroed                                                                                                                                                                                       
Soroe                                                                                                                                                                                         
Stevns                                                                                                                                                                                        
Vordingborg                                                                                                                                                                                   
/;                                                                                                                                                                                            
                                                                                                                                                                                              
SET REGSYD(AAA)                                                                                                                                                                               
/                                                                                                                                                                                             
Assens                                                                                                                                                                                        
Billund                                                                                                                                                                                       
Esbjerg                                                                                                                                                                                       
Fanoe                                                                                                                                                                                         
Faaborg-Midtfyn                                                                                                                                                                               
Fredericia                                                                                                                                                                                    
Haderslev                                                                                                                                                                                     
Kerteminde                                                                                                                                                                                    
Kolding                                                                                                                                                                                       
Langeland                                                                                                                                                                                     
Middelfart                                                                                                                                                                                    
Nordfyns                                                                                                                                                                                      
Nyborg                                                                                                                                                                                        
Odense                                                                                                                                                                                        
Svendborg                                                                                                                                                                                     
Soenderborg                                                                                                                                                                                   
Toender                                                                                                                                                                                       
Varde                                                                                                                                                                                         
Vejen                                                                                                                                                                                         
Vejle                                                                                                                                                                                         
Aeroe                                                                                                                                                                                         
Aabenraa                                                                                                                                                                                      
/;                                                                                                                                                                                            
                                                                                                                                                                                              
SET REGMID(AAA)                                                                                                                                                                               
/                                                                                                                                                                                             
Favrskov                                                                                                                                                                                      
Hedensted                                                                                                                                                                                     
Herning                                                                                                                                                                                       
Holstebro                                                                                                                                                                                     
Horsens                                                                                                                                                                                       
Ikast-Brande                                                                                                                                                                                  
Lemvig                                                                                                                                                                                        
Norddjurs                                                                                                                                                                                     
Odder                                                                                                                                                                                         
Randers                                                                                                                                                                                       
Ringkoebing-Skjern                                                                                                                                                                            
Samsoe                                                                                                                                                                                        
Silkeborg                                                                                                                                                                                     
Skanderborg                                                                                                                                                                                   
Skive                                                                                                                                                                                         
Syddjurs                                                                                                                                                                                      
Struer                                                                                                                                                                                        
Viborg                                                                                                                                                                                        
Aarhus                                                                                                                                                                                        
/;                                                                                                                                                                                            
                                                                                                                                                                                              
SET REGNORD(AAA)                                                                                                                                                                              
/                                                                                                                                                                                             
Broenderslev                                                                                                                                                                                  
Frederikshavn                                                                                                                                                                                 
Hjoerring                                                                                                                                                                                     
Jammerbugt                                                                                                                                                                                    
Laesoe                                                                                                                                                                                        
Mariagerfjord                                                                                                                                                                                 
Morsoe                                                                                                                                                                                        
Rebild                                                                                                                                                                                        
Thisted                                                                                                                                                                                       
Vesthimmerlands                                                                                                                                                                               
Aalborg                                                                                                                                                                                       
/;                                                                                                                                                                                            
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
SET APROCKAPNEW(YYY,AAA,PROC)     'Areas for possible location of new Proc or capacity expansion of existing Proc'                                                                            
*This is stablished according to economy of scale, where large plants can only be located when heat demand is high                                                                            
                                                                                                                                                                                              
/                                                                                                                                                                                             
***CO2                                                                                                                                                                                        
2020                                                                                                                       .    Aarhus                        .    CO2_DAC_20                 
2025                                                                                                                       .    Aarhus                        .    CO2_DAC_25                 
2030                                                                                                                       .    Aarhus                        .    CO2_DAC_30                 
2035                                                                                                                       .    Aarhus                        .    CO2_DAC_35                 
2040                                                                                                                       .    Aarhus                        .    CO2_DAC_40                 
2045                                                                                                                       .    Aarhus                        .    CO2_DAC_45                 
2050                                                                                                                       .    Aarhus                        .    CO2_DAC_50                 
*                                                                                                                                                                                             
2020                                                                                                                       .    Aarhus                        .    CO2_STO                    
2025                                                                                                                       .    Aarhus                        .    CO2_STO                    
2030                                                                                                                       .    Aarhus                        .    CO2_STO                    
2035                                                                                                                       .    Aarhus                        .    CO2_STO                    
2040                                                                                                                       .    Aarhus                        .    CO2_STO                    
2045                                                                                                                       .    Aarhus                        .    CO2_STO                    
2050                                                                                                                       .    Aarhus                        .    CO2_STO                    
                                                                                                                                                                                              
* OBS FF                                                                                                                                                                                      
$ifi not %baloptCCS%==yes $goto NO_CCS                                                                                                                                                        
2020                                                                                                                       .    Kalundborg                    .    CO2_Seq_20                 
2025                                                                                                                       .    Kalundborg                    .    CO2_Seq_25                 
2030                                                                                                                       .    Kalundborg                    .    CO2_Seq_30                 
2035                                                                                                                       .    Kalundborg                    .    CO2_Seq_35                 
2040                                                                                                                       .    Kalundborg                    .    CO2_Seq_40                 
2045                                                                                                                       .    Kalundborg                    .    CO2_Seq_45                 
2050                                                                                                                       .    Kalundborg                    .    CO2_Seq_50                 
$label NO_CCS                                                                                                                                                                                 
                                                                                                                                                                                              
*OBS FF                                                                                                                                                                                       
$ifi not %baloptgasbridge%==yes $goto NO_BIOGAS                                                                                                                                               
2020                                                                                                                       .    Aarhus                        .    Digestion_Tank_20          
2025                                                                                                                       .    Aarhus                        .    Digestion_Tank_25          
2030                                                                                                                       .    Aarhus                        .    Digestion_Tank_30          
2035                                                                                                                       .    Aarhus                        .    Digestion_Tank_35          
2040                                                                                                                       .    Aarhus                        .    Digestion_Tank_40          
2045                                                                                                                       .    Aarhus                        .    Digestion_Tank_45          
2050                                                                                                                       .    Aarhus                        .    Digestion_Tank_50          
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Methanation_20             
2025                                                                                                                       .    Aarhus                        .    Methanation_25             
2030                                                                                                                       .    Aarhus                        .    Methanation_30             
2035                                                                                                                       .    Aarhus                        .    Methanation_35             
2040                                                                                                                       .    Aarhus                        .    Methanation_40             
2045                                                                                                                       .    Aarhus                        .    Methanation_45             
2050                                                                                                                       .    Aarhus                        .    Methanation_50             
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_20        
2025                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_25        
2030                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_30        
2035                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_35        
2040                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_40        
2045                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_45        
2050                                                                                                                       .    Aarhus                        .    Biogas_Upgrading_50        
                                                                                                                                                                                              
$label NO_BIOGAS                                                                                                                                                                              
                                                                                                                                                                                              
***TG                                                                                                                                                                                         
2020                                                                                                                       .    Aarhus                        .    TG_20                      
2025                                                                                                                       .    Aarhus                        .    TG_25                      
2030                                                                                                                       .    Aarhus                        .    TG_30                      
2035                                                                                                                       .    Aarhus                        .    TG_35                      
2040                                                                                                                       .    Aarhus                        .    TG_40                      
2045                                                                                                                       .    Aarhus                        .    TG_45                      
2050                                                                                                                       .    Aarhus                        .    TG_50                      
***Methanol                                                                                                                                                                                   
2020                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_20   
2025                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_25   
2030                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_30   
2035                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_35   
2040                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_40   
2045                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_45   
2050                                                                                                                       .    Aarhus                        .    Methanol_synthesis_TG_50   
*                                                                                                                                                                                             
2020                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_20     
2025                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_25     
2030                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_30     
2035                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_35     
2040                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_40     
2045                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_45     
2050                                                                                                                       .    Aarhus                        .    EMethanol_synthesis_50     
*                                                                                                                                                                                             
2020                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_20       
2025                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_25       
2030                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_30       
2035                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_35       
2040                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_40       
2045                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_45       
2050                                                                                                                       .    Aarhus                        .    EMethanol_Upgrade_50       
***Ammonia                                                                                                                                                                                    
2020                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_20       
2025                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_25       
2030                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_30       
2035                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_35       
2040                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_40       
2045                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_45       
2050                                                                                                                       .    Aarhus                        .    Ammonia_Synthesis_50       
***Jet and oil products                                                                                                                                                                       
2020                                                                                                                       .    Aarhus                        .    BioJet_20                  
2025                                                                                                                       .    Aarhus                        .    BioJet_25                  
2030                                                                                                                       .    Aarhus                        .    BioJet_30                  
2035                                                                                                                       .    Aarhus                        .    BioJet_35                  
2040                                                                                                                       .    Aarhus                        .    BioJet_40                  
2045                                                                                                                       .    Aarhus                        .    BioJet_45                  
2050                                                                                                                       .    Aarhus                        .    BioJet_50                  
*                                                                                                                                                                                             
2020                                                                                                                       .    Aarhus                        .    BioJet_H2_20               
2025                                                                                                                       .    Aarhus                        .    BioJet_H2_25               
2030                                                                                                                       .    Aarhus                        .    BioJet_H2_30               
2035                                                                                                                       .    Aarhus                        .    BioJet_H2_35               
2040                                                                                                                       .    Aarhus                        .    BioJet_H2_40               
2045                                                                                                                       .    Aarhus                        .    BioJet_H2_45               
2050                                                                                                                       .    Aarhus                        .    BioJet_H2_50               
*                                                                                                                                                                                             
2020                                                                                                                       .    Aarhus                        .    E_FT_20                    
2025                                                                                                                       .    Aarhus                        .    E_FT_25                    
2030                                                                                                                       .    Aarhus                        .    E_FT_30                    
2035                                                                                                                       .    Aarhus                        .    E_FT_35                    
2040                                                                                                                       .    Aarhus                        .    E_FT_40                    
2045                                                                                                                       .    Aarhus                        .    E_FT_45                    
2050                                                                                                                       .    Aarhus                        .    E_FT_50                    
                                                                                                                                                                                              
2020                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2025                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2030                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2035                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2040                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2045                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
2050                                                                                                                       .    Ballerup                      .    Untouched_Forest_HOV       
                                                                                                                                                                                              
2020                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2025                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2030                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2035                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2040                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2045                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
2050                                                                                                                       .    Faxe                          .    Untouched_Forest_SJA       
                                                                                                                                                                                              
2020                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2025                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2030                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2035                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2040                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2045                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
2050                                                                                                                       .    Assens                        .    Untouched_Forest_SYD       
                                                                                                                                                                                              
2020                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2025                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2030                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2035                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2040                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2045                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
2050                                                                                                                       .    Favrskov                      .    Untouched_Forest_MID       
                                                                                                                                                                                              
2020                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2025                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2030                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2035                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2040                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2045                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
2050                                                                                                                       .    Broenderslev                  .    Untouched_Forest_NOR       
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Wood_Production            
2025                                                                                                                       .    Aarhus                        .    Wood_Production            
2030                                                                                                                       .    Aarhus                        .    Wood_Production            
2035                                                                                                                       .    Aarhus                        .    Wood_Production            
2040                                                                                                                       .    Aarhus                        .    Wood_Production            
2045                                                                                                                       .    Aarhus                        .    Wood_Production            
2050                                                                                                                       .    Aarhus                        .    Wood_Production            
                                                                                                                                                                                              
2020                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2025                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2030                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2035                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2040                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2045                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
2050                                                                                                                       .    Ballerup                      .    C_Rich_Soils_Extraction_HOV
                                                                                                                                                                                              
2020                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2025                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2030                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2035                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2040                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2045                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
2050                                                                                                                       .    Faxe                          .    C_Rich_Soils_Extraction_SJA
                                                                                                                                                                                              
2020                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2025                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2030                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2035                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2040                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2045                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
2050                                                                                                                       .    Assens                        .    C_Rich_Soils_Extraction_SYD
                                                                                                                                                                                              
2020                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2025                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2030                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2035                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2040                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2045                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
2050                                                                                                                       .    Favrskov                      .    C_Rich_Soils_Extraction_MID
                                                                                                                                                                                              
2020                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2025                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2030                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2035                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2040                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2045                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
2050                                                                                                                       .    Broenderslev                  .    C_Rich_Soils_Extraction_NOR
                                                                                                                                                                                              
2020                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2025                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2030                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2035                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2040                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2045                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
2050                                                                                                                       .    Ballerup                      .    New_Productive_Forest_HOV  
                                                                                                                                                                                              
2020                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2025                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2030                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2035                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2040                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2045                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
2050                                                                                                                       .    Faxe                          .    New_Productive_Forest_SJA  
                                                                                                                                                                                              
2020                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2025                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2030                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2035                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2040                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2045                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
2050                                                                                                                       .    Assens                        .    New_Productive_Forest_SYD  
                                                                                                                                                                                              
2020                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2025                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2030                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2035                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2040                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2045                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
2050                                                                                                                       .    Favrskov                      .    New_Productive_Forest_MID  
                                                                                                                                                                                              
2020                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2025                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2030                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2035                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2040                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2045                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
2050                                                                                                                       .    Broenderslev                  .    New_Productive_Forest_NOR  
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2025                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2030                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2035                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2040                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2045                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
2050                                                                                                                       .    Aarhus                        .    Wheat_Agriculture          
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2025                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2030                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2035                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2040                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2045                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
2050                                                                                                                       .    Aarhus                        .    Barley_Agriculture         
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2025                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2030                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2035                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2040                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2045                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
2050                                                                                                                       .    Aarhus                        .    Rye_Agriculture            
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2025                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2030                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2035                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2040                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2045                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
2050                                                                                                                       .    Aarhus                        .    Oat_Agriculture            
                                                                                                                                                                                              
2020                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_20         
2025                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_25         
2030                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_30         
2035                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_35         
2040                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_40         
2045                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_45         
2050                                                                                                                       .    Aarhus                        .    Pyrolysis_Straw_50         
                                                                                                                                                                                              
/                                                                                                                                                                                             
;                                                                                                                                                                                             
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'CO2_DAC_20')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_20');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_25')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_25');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_30')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_30');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_35')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_35');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_40')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_40');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_45')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_45');                                                                                                        
APROCKAPNEW(Y,AAA,'CO2_DAC_50')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_50');                                                                                                        
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'CO2_STO')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_STO');                                                                                                              
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'CO2_Seq_20')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_20');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_25')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_25');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_30')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_30');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_35')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_35');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_40')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_40');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_45')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_45');                                                                                                 
APROCKAPNEW(Y,AAA,'CO2_Seq_50')$CCSAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Kalundborg','CO2_Seq_50');                                                                                                 
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Digestion_Tank_20')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_20');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_25')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_25');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_30')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_30');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_35')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_35');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_40')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_40');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_45')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_45');                                                                                          
APROCKAPNEW(Y,AAA,'Digestion_Tank_50')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_50');                                                                                          
APROCKAPNEW(Y,AAA,'Methanation_20')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_20');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_25')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_25');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_30')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_30');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_35')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_35');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_40')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_40');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_45')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_45');                                                                                                
APROCKAPNEW(Y,AAA,'Methanation_50')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_50');                                                                                                
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_20')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_20');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_25')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_25');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_30')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_30');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_35')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_35');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_40')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_40');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_45')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_45');                                                                                      
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_50')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_50');                                                                                      
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'TG_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_20');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_25');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_30');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_35');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_40');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_45');                                                                                                               
APROCKAPNEW(Y,AAA,'TG_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_50');                                                                                                               
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_20');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_25');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_30');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_35');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_40');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_45');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_50');                                                                         
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_20');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_25');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_30');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_35');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_40');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_45');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_50');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_20');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_25');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_30');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_35');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_40');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_45');                                                                                 
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_50');                                                                                 
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_20');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_25');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_30');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_35');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_40');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_45');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_50');                                                                                 
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'BioJet_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_20');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_25');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_30');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_35');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_40');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_45');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_50');                                                                                                       
APROCKAPNEW(Y,AAA,'BioJet_H2_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_20');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_25');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_30');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_35');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_40');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_45');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_50');                                                                                                 
APROCKAPNEW(Y,AAA,'E_FT_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_20');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_25');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_30');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_35');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_40');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_45');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_50');                                                                                                           
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Untouched_Forest_HOV')$REGHOV(AAA)=APROCKAPNEW(Y,'Ballerup','Untouched_Forest_HOV');                                                                                       
APROCKAPNEW(Y,AAA,'Untouched_Forest_SJA')$REGSJA(AAA)=APROCKAPNEW(Y,'Faxe','Untouched_Forest_SJA');                                                                                           
APROCKAPNEW(Y,AAA,'Untouched_Forest_SYD')$REGSYD(AAA)=APROCKAPNEW(Y,'Assens','Untouched_Forest_SYD');                                                                                         
APROCKAPNEW(Y,AAA,'Untouched_Forest_MID')$REGMID(AAA)=APROCKAPNEW(Y,'Favrskov','Untouched_Forest_MID');                                                                                       
APROCKAPNEW(Y,AAA,'Untouched_Forest_NOR')$REGNORD(AAA)=APROCKAPNEW(Y,'Broenderslev','Untouched_Forest_NOR');                                                                                  
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction_HOV')$REGHOV(AAA)=APROCKAPNEW(Y,'Ballerup','C_Rich_Soils_Extraction_HOV');                                                                         
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction_SJA')$REGSJA(AAA)=APROCKAPNEW(Y,'Faxe','C_Rich_Soils_Extraction_SJA');                                                                             
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction_SYD')$REGSYD(AAA)=APROCKAPNEW(Y,'Assens','C_Rich_Soils_Extraction_SYD');                                                                           
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction_MID')$REGMID(AAA)=APROCKAPNEW(Y,'Favrskov','C_Rich_Soils_Extraction_MID');                                                                         
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction_NOR')$REGNORD(AAA)=APROCKAPNEW(Y,'Broenderslev','C_Rich_Soils_Extraction_NOR');                                                                    
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'New_Productive_Forest_HOV')$REGHOV(AAA)=APROCKAPNEW(Y,'Ballerup','New_Productive_Forest_HOV');                                                                             
APROCKAPNEW(Y,AAA,'New_Productive_Forest_SJA')$REGSJA(AAA)=APROCKAPNEW(Y,'Faxe','New_Productive_Forest_SJA');                                                                                 
APROCKAPNEW(Y,AAA,'New_Productive_Forest_SYD')$REGSYD(AAA)=APROCKAPNEW(Y,'Assens','New_Productive_Forest_SYD');                                                                               
APROCKAPNEW(Y,AAA,'New_Productive_Forest_MID')$REGMID(AAA)=APROCKAPNEW(Y,'Favrskov','New_Productive_Forest_MID');                                                                             
APROCKAPNEW(Y,AAA,'New_Productive_Forest_NOR')$REGNORD(AAA)=APROCKAPNEW(Y,'Broenderslev','New_Productive_Forest_NOR');                                                                        
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Wood_Production')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Wood_Production');                                                                                              
APROCKAPNEW(Y,AAA,'Wheat_Agriculture')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Wheat_Agriculture');                                                                                          
APROCKAPNEW(Y,AAA,'Barley_Agriculture')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Barley_Agriculture');                                                                                        
APROCKAPNEW(Y,AAA,'Oat_Agriculture')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Oat_Agriculture');                                                                                              
APROCKAPNEW(Y,AAA,'Rye_Agriculture')$AAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Rye_Agriculture');                                                                                              
                                                                                                                                                                                              
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_20');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_25');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_30');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_35');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_40');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_45');                                                                                     
APROCKAPNEW(Y,AAA,'Pyrolysis_Straw_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Pyrolysis_Straw_50');                                                                                     
